[project]
name = "circle-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Xiaohua Zhang", email = "xiaohua.dev@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
circle-test = "circle_test:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]
