version: '2.1'
orbs:
  python: circleci/python@3.0.0
jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: uv
      - run:
          name: Run tests
          command: |
            uv run pytest
workflows:
  main:
    jobs:
      - build
